forge 'https://forge.puppet.com'
mod 'bodgit/bodgitlib', '2.0.1'
mod 'herculesteam/augeasproviders', '2.4.1'
mod 'herculesteam/augeasproviders_base', '2.1.0'
mod 'herculesteam/augeasproviders_core', '2.6.0'
mod 'herculesteam/augeasproviders_pam', '2.2.1'
mod 'herculesteam/augeasproviders_ssh', commit: 'e4eee3726d0472cba1d2d66a2d09031f1d100914', git: 'https://github.com/hercules-team/augeasproviders_ssh'
mod 'inkblot/ipcalc', '2.2.0'
mod 'ncsa/openafs', tag: 'v0.2.5', git: 'https://github.com/ncsa/puppet-openafs'
mod 'ncsa/pam_access', tag: 'ncsa/1.1.0', git: 'https://github.com/ncsa/puppet-pam_access'
mod 'ncsa/profile_additional_packages', tag: 'v0.3.0', git: 'https://github.com/ncsa/puppet-profile_additional_packages'
mod 'ncsa/profile_allow_ssh_from_bastion', tag: 'v0.2.3', git: 'https://github.com/ncsa/puppet-profile_allow_ssh_from_bastion'
mod 'ncsa/profile_audit', tag: 'v0.1.7', git: 'https://github.com/ncsa/puppet-profile_audit'
mod 'ncsa/profile_dns_cache', tag: 'v1.1.2', git: 'https://github.com/ncsa/puppet-profile_dns_cache'
mod 'ncsa/profile_email', tag: 'v0.2.2', git: 'https://github.com/ncsa/puppet-profile_email'
mod 'ncsa/profile_firewall', tag: 'v1.0.6', git: 'https://github.com/ncsa/puppet-profile_firewall'
mod 'ncsa/profile_monitoring', tag: 'v0.1.9', git: 'https://github.com/ncsa/puppet-profile_monitoring'
mod 'ncsa/profile_motd', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_motd'
mod 'ncsa/profile_nfs_client', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_nfs_client'
mod 'ncsa/profile_pam_access', tag: 'v0.0.6', git: 'https://github.com/ncsa/puppet-profile_pam_access'
mod 'ncsa/profile_puppet_agent', tag: 'v0.1.2', git: 'https://github.com/ncsa/puppet-profile_puppet_agent'
mod 'ncsa/profile_puppet_master', tag: 'v0.1.2', git: 'https://github.com/ncsa/puppet-profile_puppet_master'
mod 'ncsa/profile_rsyslog', tag: 'v0.1.4', git: 'https://github.com/ncsa/puppet-profile_rsyslog'
mod 'ncsa/profile_selinux', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_selinux'
mod 'ncsa/profile_sudo', tag: 'v0.1.2', git: 'https://github.com/ncsa/puppet-profile_sudo'
mod 'ncsa/profile_system_auth', tag: 'v0.3.7', git: 'https://github.com/ncsa/puppet-profile_system_auth'
mod 'ncsa/profile_timesync', tag: 'v0.2.1', git: 'https://github.com/ncsa/puppet-profile_timesync'
mod 'ncsa/profile_timezone', tag: 'v0.2.1', git: 'https://github.com/ncsa/puppet-profile_timezone'
mod 'ncsa/profile_update_os', tag: 'v0.3.6', git: 'https://github.com/ncsa/puppet-profile_update_os'
mod 'ncsa/profile_virtual', tag: 'v0.1.1', git: 'https://github.com/ncsa/puppet-profile_virtual'
mod 'ncsa/profile_website', tag: 'v0.1.1', git: 'https://github.com/ncsa/puppet-profile_website'
mod 'ncsa/profile_xcat', tag: 'v1.1.5', git: 'https://github.com/ncsa/puppet-profile_xcat.git'
mod 'ncsa/rhsm', tag: 'v0.1.2', git: 'https://github.com/ncsa/puppet-rhsm'
mod 'ncsa/sshd', tag: 'v0.3.4', git: 'https://github.com/ncsa/puppet-sshd'
mod 'ncsa/sssd', tag: 'v3.0.2', git: 'https://github.com/ncsa/puppet-sssd'
mod 'ncsa/telegraf', tag: 'v3.1.1', git: 'https://github.com/ncsa/puppet-telegraf.git'
mod 'puppet/chrony', '1.0.0'
mod 'puppet/epel', '3.0.1'
mod 'puppet/letsencrypt', '6.0.0'
mod 'puppet/rsyslog', '5.2.0'
mod 'puppet/yum', '5.1.0'
mod 'puppetlabs/apache', '6.4.0'
mod 'puppetlabs/concat', '6.4.0'
mod 'puppetlabs/firewall', '3.0.0'
mod 'puppetlabs/inifile', '4.4.0'
mod 'puppetlabs/mailalias_core', '1.0.6'
mod 'puppetlabs/stdlib', '6.3.0'
mod 'puppetlabs/xinetd', '3.3.0'
mod 'richardc/datacat', '0.6.2'
mod 'saz/sudo', '6.0.0'
mod 'saz/timezone', '6.1.0'
mod 'southalc/vault_secrets', '0.4.2'
mod 'thrnio/ip', '1.0.1'
mod 'woodsbw/augeasfacter', commit: '9aea81311d277ed7ff1e8f2d4f79d13cd25f6ded', git: 'https://github.com/woodsbw/augeasfacter'
