forge 'https://forge.puppet.com'
mod 'bodgit/bodgitlib', '2.0.1'
mod 'herculesteam/augeasfacter', commit: 'b5e2ebf740036c5480386f4d0ef362015bfcac55', git: 'https://github.com/hercules-team/augeasfacter'
mod 'herculesteam/augeasproviders', '2.4.1'
mod 'herculesteam/augeasproviders_base', '2.1.0'
mod 'herculesteam/augeasproviders_core', '2.6.0'
mod 'herculesteam/augeasproviders_pam', '2.2.1'
mod 'herculesteam/augeasproviders_ssh', commit: 'e4eee3726d0472cba1d2d66a2d09031f1d100914', git: 'https://github.com/hercules-team/augeasproviders_ssh'
mod 'herculesteam/augeasproviders_sysctl', '2.6.2'
mod 'inkblot/ipcalc', '2.2.0'
mod 'ncsa/gpfs', tag: 'v2.1.7', git: 'https://github.com/ncsa/puppet-spectrumscale.git'
mod 'ncsa/lvm', tag: 'v1.4.0', git: 'https://github.com/ncsa/puppet-lvm.git'
mod 'ncsa/openafs', tag: 'v0.2.5', git: 'https://github.com/ncsa/puppet-openafs'
mod 'ncsa/pam_access', tag: 'ncsa/1.1.0', git: 'https://github.com/ncsa/puppet-pam_access'
mod 'ncsa/profile_acctd', tag: 'v1.2.1', git: 'https://github.com/ncsa/puppet-profile_acctd'
mod 'ncsa/profile_additional_packages', tag: 'v0.4.1', git: 'https://github.com/ncsa/puppet-profile_additional_packages'
mod 'ncsa/profile_allow_ssh_from_bastion', tag: 'v0.2.4', git: 'https://github.com/ncsa/puppet-profile_allow_ssh_from_bastion'
mod 'ncsa/profile_audit', tag: 'v0.1.17', git: 'https://github.com/ncsa/puppet-profile_audit'
mod 'ncsa/profile_backup', tag: 'v0.0.9', git: 'https://github.com/ncsa/puppet-profile_backup'
mod 'ncsa/profile_dns_cache', tag: 'v1.1.4', git: 'https://github.com/ncsa/puppet-profile_dns_cache'
mod 'ncsa/profile_duo', tag: 'v1.0.5', git: 'https://github.com/ncsa/puppet-profile_duo'
mod 'ncsa/profile_email', tag: 'v0.2.5', git: 'https://github.com/ncsa/puppet-profile_email'
mod 'ncsa/profile_firewall', tag: 'v1.1.2', git: 'https://github.com/ncsa/puppet-profile_firewall'
mod 'ncsa/profile_globus', tag: 'v0.5.2', git: 'https://github.com/ncsa/puppet-profile_globus'
mod 'ncsa/profile_gpfs_client', tag: 'v0.1.1', git: 'https://github.com/ncsa/puppet-profile_gpfs_client.git'
mod 'ncsa/profile_gpu', tag: 'v1.0.4', git: 'https://github.com/ncsa/puppet-profile_gpu.git'
mod 'ncsa/profile_hardening', tag: 'v0.4.0', git: 'https://github.com/ncsa/puppet-profile_hardening'
mod 'ncsa/profile_hostbased_ssh', tag: 'v1.0.3', git: 'https://github.com/ncsa/puppet-profile_hostbased_ssh'
mod 'ncsa/profile_hosts', tag: 'v0.1.1', git: 'https://github.com/ncsa/puppet-profile_hosts'
mod 'ncsa/profile_java', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_java.git'
mod 'ncsa/profile_lmod', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_lmod.git'
mod 'ncsa/profile_lustre', tag: 'v2.0.2',  git: 'https://github.com/ncsa/puppet-profile_lustre'
mod 'ncsa/profile_lvm', tag: 'v1.0.0',  git: 'https://github.com/ncsa/puppet-profile_lvm'
mod 'ncsa/profile_monitoring', tag: 'v0.3.2', git: 'https://github.com/ncsa/puppet-profile_monitoring'
mod 'ncsa/profile_motd', tag: 'v0.3.2', git: 'https://github.com/ncsa/puppet-profile_motd'
mod 'ncsa/profile_mysql_server', tag: 'v0.1.1', git: 'https://github.com/ncsa/puppet-profile_mysql_server'
mod 'ncsa/profile_network', tag: 'v1.0.0', git: 'https://github.com/ncsa/puppet-profile_network.git'
mod 'ncsa/profile_nfs_client', tag: 'v0.2.0', git: 'https://github.com/ncsa/puppet-profile_nfs_client'
mod 'ncsa/profile_ondemand', tag: 'v1.0.3', git: 'https://github.com/ncsa/puppet-profile_ondemand.git'
mod 'ncsa/profile_pam_access', tag: 'v0.0.6', git: 'https://github.com/ncsa/puppet-profile_pam_access'
mod 'ncsa/profile_postgres_server', tag: 'v0.1.1', git: 'https://github.com/ncsa/puppet-profile_postgres_server'
mod 'ncsa/profile_puppet_agent', tag: 'v0.1.4', git: 'https://github.com/ncsa/puppet-profile_puppet_agent'
mod 'ncsa/profile_puppet_master', tag: 'v0.1.6', git: 'https://github.com/ncsa/puppet-profile_puppet_master'
mod 'ncsa/profile_rsyslog', tag: 'v0.3.0', git: 'https://github.com/ncsa/puppet-profile_rsyslog'
mod 'ncsa/profile_selinux', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_selinux'
mod 'ncsa/profile_session_log', tag: 'v1.0.0', git: 'https://github.com/ncsa/puppet-profile_session_log.git'
mod 'ncsa/profile_slurm', tag: 'v2.1.0', git: 'https://github.com/ncsa/puppet-profile_slurm.git'
mod 'ncsa/profile_sudo', tag: 'v0.1.2', git: 'https://github.com/ncsa/puppet-profile_sudo'
mod 'ncsa/profile_system_auth', tag: 'v0.4.0', git: 'https://github.com/ncsa/puppet-profile_system_auth'
mod 'ncsa/profile_timesync', tag: 'v0.2.2', git: 'https://github.com/ncsa/puppet-profile_timesync'
mod 'ncsa/profile_timezone', tag: 'v0.2.1', git: 'https://github.com/ncsa/puppet-profile_timezone'
mod 'ncsa/profile_umask', tag: 'v0.0.2', git: 'https://github.com/ncsa/puppet-profile_umask'
mod 'ncsa/profile_update_os', tag: 'v0.4.3', git: 'https://github.com/ncsa/puppet-profile_update_os'
mod 'ncsa/profile_user_environment', tag: 'v0.2.0', git: 'https://github.com/ncsa/puppet-profile_user_environment'
mod 'ncsa/profile_virtual', tag: 'v0.1.1', git: 'https://github.com/ncsa/puppet-profile_virtual'
mod 'ncsa/profile_website', tag: 'v0.1.6', git: 'https://github.com/ncsa/puppet-profile_website'
mod 'ncsa/profile_xcat', tag: 'v1.1.10', git: 'https://github.com/ncsa/puppet-profile_xcat.git'
mod 'ncsa/rhsm', tag: 'v0.1.7', git: 'https://github.com/ncsa/puppet-rhsm'
mod 'ncsa/sshd', tag: 'v0.5.1', git: 'https://github.com/ncsa/puppet-sshd'
mod 'ncsa/sssd', tag: 'v3.0.2', git: 'https://github.com/ncsa/puppet-sssd'
mod 'ncsa/telegraf', tag: 'ncsa/v0.1.1', git: 'https://github.com/ncsa/puppet-telegraf.git'
mod 'osc/openondemand', '4.2.1'
mod 'puppet-alternatives', '4.0.0'
mod 'puppet-archive', '6.0.2'
mod 'puppet/chrony', '1.0.0'
mod 'puppet/epel', '4.1.0'
mod 'puppet/letsencrypt', '8.0.2'
mod 'puppet/logrotate', '6.0.0'
mod 'puppet/rsyslog', '5.2.0'
mod 'puppet/systemd', '5.1.0'
mod 'puppet/yum', '5.3.0'
mod 'puppetlabs/apache', '6.4.0'
mod 'puppetlabs/concat', '6.4.0'
mod 'puppetlabs/firewall', '4.0.1'
mod 'puppetlabs/inifile', '4.4.0'
mod 'puppetlabs/mailalias_core', '1.0.6'
mod 'puppetlabs/mysql', '12.0.3'
mod 'puppetlabs/stdlib', '6.3.0'
mod 'puppetlabs/vcsrepo', '5.0.0'
mod 'puppetlabs/xinetd', '3.3.0'
mod 'richardc/datacat', '0.6.2'
mod 'saz/sudo', '6.0.0'
mod 'saz/timezone', '6.1.0'
mod 'srstevens/gcsv5', tag: 'v2.1.9', git: 'https://github.com/srstevens/puppet-gcsv5'
mod 'thrnio/ip', '1.0.1'
mod 'treydock/apptainer', '2.0.0'
mod 'treydock/lmod', '3.2.0'
mod 'treydock/munge', '4.1.0'
mod 'treydock/nhc', '5.0.0'
# These versions of treydock/slurm* are updated for Slurm v23.11 support. They should also
# work for Slurm v22.05 and v23.02 but NCSA has not tested them with those. Consider using
# the earlier modules versions specified in comments below if still using those earlier
# versions of Slurm.
mod 'treydock/slurm', '4.0.1'  # (previously 2.2.0) 
mod 'treydock/slurm_providers', '0.14.1'  # (previously 0.12.3) 
